### ISSUE TITLE
[Colours] Dark Theme LBC

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark-tokens#57]
Create a Dark Theme LBC 

- [x] Workshop UI 
- [x] Valid & Test
- [x] Migrate

**Comment by solygambas** [comment]
I created a dedicated branch in the Figma plugin so that you can experiment.

**Comment by Bibisirius** [comment]
The dark theme is available : [here ](https://www.figma.com/file/mi27uTCA1MaVpKCKoN6GcK/leboncoin---Brand-Foundations?type=design&node-id=519-1340&mode=design&t=q86WfinZvfY9e5Hm-11)

**Comment by solygambas** [comment]
The dark theme is available in the Figma plugin too.
