### ISSUE TITLE
[Colours] Update the foundations of LBC (Light theme)

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark-tokens#58]
Update the foundation of LBC :

- Blueberry 
- Nighshade
- Neutral
- Outline

**Comment by Bibisirius** [comment]
Done 👍

**Comment by solygambas** [comment]
Thanks, done for the Figma plugin too.

**Comment by Bibisirius** [comment]
Warning: The outline colour will change. I'll let you know as soon as it's done.
