### ISSUE TITLE
[Icon] Removing the avatar icon

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark-tokens#60]
Missing the[ avatar](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=316-8102&mode=design&t=XVfYrk60lnGo2FI1-11) icon

Thanks 👍

**Comment by solygambas** [comment]
@Bibisirius It seems to me that the avatar doesn't align with our new definition of an icon. Could you please initiate a discussion with developers on Slack about this?

**Comment by solygambas** [comment]
It seems that it's already in the repository, but it doesn't display well on the web due to its multicolored nature.
