### ISSUE TITLE
[Icon] Fixing the wifi icon

### ISSUE THREAD

**Issue by solygambas** [adevinta/spark-tokens#65]
The wifi icon has an issue with its centering and roundness, which is affecting its visual appearance. Currently, the base of the icon appears slightly off-center and not completely rounded.

**Comment by Bibisirius** [comment]
Check 👍 

We need to check if it's OK. There maybe a figma bug

**Comment by solygambas** [comment]
Fixed on the repo, feel free to use it for figma :) 
https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Wifi.svg
