### ISSUE TITLE
[Icons] Consolidating duplicate icons: unifying names and categories

### ISSUE THREAD

**Issue by solygambas** [adevinta/spark-tokens#71]
This issue addresses duplicate icons on Figma. 

Here is the list of duplicates:

1. [Brand.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Brand.svg) and [Model.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Model.svg) (medias)
2. [OfferType.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/OfferType.svg) and [Animals.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Animals.svg) (animals and holidays)
3. [Start.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Start.svg) and [Arrival.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Arrival.svg) (holidays)
4. [Univers.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Univers.svg) and [Capacity.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Capacity.svg) (mode and holidays)
5. [Years.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Years.svg) and [CalendarCriterias.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/CalendarCriterias.svg) (vehicles and holidays)

The goal is to choose a unique name and category for each icon, enhancing clarity and consistency within our collection.

**Comment by solygambas** [comment]
@Bibisirius I've included the links to the visuals :)

**Comment by solygambas** [comment]
From rav-next:
- messaging/src/pages/ClassifiedAd/common/constants/criteria.ts
- pages/ClassifiedAd/common/constants/criteria.ts

```
import {
  Animals,
  Arrival,
  Brand,
  CalendarCriterias,
  Capacity,
  OfferType,
  Univers,
} from '@spark-ui/icons'
```

Candidates for deprecation:

1. [Model.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Model.svg) (no instance)
2. [Start.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Start.svg) (no instance)
3. [Years.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Years.svg) (no instance)

Remaining duplicates:

1. [OfferType.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/OfferType.svg) and [Animals.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Animals.svg) (animals and holidays)
2. [Univers.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Univers.svg) and [Capacity.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Capacity.svg) (mode and holidays)

We need to clarify this with the UI designer in charge of this scope.

**Comment by Bibisirius** [comment]
[Start.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Start.svg) and [Arrival.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Arrival.svg) (holidays) Just keep start and delete arrival

**Comment by turolopezsanabria** [comment]
hey @solygambas can we include this work as part of the work of the Iconography guild, led by Yaara, [this is the channel](https://adevinta.slack.com/archives/C060FV8NRSN)?

**Comment by Bibisirius** [comment]
Done

**Comment by turolopezsanabria** [comment]
Closing this ticket while waiting for Madison to unify [Univers.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Univers.svg) and [Capacity.svg](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Capacity.svg)

Reminder that Yaara is leading icons.
